http:
  routers:
    pmox1:
      rule: "Host(`pve.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - lan-only
      service: pmox1
      tls:
        certResolver: letsencrypt

    pihole:
      rule: "Host(`pihole.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - lan-only
      service: pihole
      tls:
        certResolver: letsencrypt

    arcane:
      rule: "Host(`arcane.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - lan-only
      service: arcane
      tls:
        certResolver: letsencrypt

  # serversTransports:
  #   insecureSkipVerify:
  #     insecureSkipVerify: true

  services:
    pmox1:
      loadBalancer:
        serversTransport: insecureSkipVerify
        servers:
          - url: "https://192.168.0.8:8006"

    pihole:
      loadBalancer:
        serversTransport: insecureSkipVerify 
        servers:
          - url: "http://192.168.0.12:80"

    arcane:
      loadBalancer:
        servers:
          - url: "http://192.168.0.11:3552"