http:
  routers:
    pmox1:
      rule: "Host(`pve.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers@file
        - lan-only@file
      service: pmox1
      tls:
        certResolver: letsencrypt

    pihole:
      rule: "Host(`pihole.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers@file
        - lan-only@file
      service: pihole
      tls:
        certResolver: letsencrypt

    arcane:
      rule: "Host(`arcane.phanee.in`)"
      entryPoints:
        - websecure
      middlewares:
        - secure-headers@file
        - lan-only@file
      service: arcane
      tls:
        certResolver: letsencrypt

  services:
    pmox1:
      loadBalancer:
        serversTransport: insecureSkipVerify
        servers:
          - url: "https://192.168.0.8:8006"

    pihole:
      loadBalancer:
        serversTransport: insecureSkipVerify
        servers:
          - url: "https://192.168.0.12"

    arcane:
      loadBalancer:
        serversTransport: insecureSkipVerify
        servers:
          - url: "https://192.168.0.11:3552"