http:
  routers:
    traefik-manager:
      rule: Host(`traefik-manager.phanee.in`)
      entryPoints:
        - websecure
      service: traefik-manager
      tls:
        certResolver: letsencrypt
  services:
    traefik-manager:
      loadBalancer:
        servers:
          - url: http://traefik-manager:5000