services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      # Don't forget to set this in your Environment
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:?}
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --protocol
      - http2
      - run
    networks:
      - traefik
    depends_on:
      traefik:
        condition: service_healthy
networks:
  traefik:
    external: true
    name: traefik
