services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      # Don't forget to set this in your Dokploy Environment
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:?}
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --protocol
      - http2
      - run
    networks:
      - homelab-network
networks:
  homelab-network:
    external: true
